language: ruby
rvm:
- 2.2
before_script:
- gem install awesome_bot
script:
- awesome_bot README.rst --white-list "https://github.com/sindresorhus/awesome","readthedocs.org","docs.pylonsproject.org","https://bitbucket.org/estin/sadisplay","bottlepy.org",zope
